### ISSUE TITLE
avh.query() returning results for platform type not in platform_type string

### ISSUE THREAD

**Issue by SBS-EREHM** [argovis/argovis_helpers#31]
When I supply the following options=params to an avh.query('argo', options=paraams, apikey...., apiroot...), I get results back for NAVIS_A too.  (NAVIS_A is not part of the platform_type string.)

`{'startDate': '2015-01-01T00:00:00Z', 'endDate': '2019-01-01T00:00:00Z', 'source': 'argo_bgc', 'polygon': [[141, 54.5], [141, 26.3], [179.9, 26.3], [179.9, 54.5], [141, 54.5]], 'data': 'cdom', 'platform_type': 'APEX,SOLO,SOLO_II,SOLO_W,SOLO_BGC,PROVOR,PROVOR_II,PROVOR_III,PROVOR_IV,PROVOR_V,PROVOR_V_JUMBO'}`

Results include profiles with the following metadata property followed by platform_type lookup for the 'argo/metdata' id.
{'id': '2903330_m0'}
NAVIS_A
{'id': '2903329_m0'}
NAVIS_A
{'id': '2903213_m0'}
NAVIS_A
{'id': '2902755_m0'}
PROVOR
{'id': '2903354_m0'}
APEX
{'id': '2902754_m0'}
PROVOR

**Note 1:** The query using negated query ~NAVIS_A returns the same results as above 

`{'startDate': '2015-01-01T00:00:00Z', 'endDate': '2019-01-01T00:00:00Z', 'source': 'argo_bgc', 'polygon': [[141, 54.5], [141, 26.3], [179.9, 26.3], [179.9, 54.5], [141, 54.5]], 'data': 'cdom', 'platform_type': '~NAVIS_A'}`

(Comment: not sure how to do an exclusionary "AND" query, e.g., exclude BOTH NAVIS_A and NAVIS_EBR....)

**Note 2**. The following query does return only the PROVOR resullts:

`{'startDate': '2015-01-01T00:00:00Z', 'endDate': '2019-01-01T00:00:00Z', 'source': 'argo_bgc', 'polygon': [[141, 54.5], [141, 26.3], [179.9, 26.3], [179.9, 54.5], [141, 54.5]], 'data': 'cdom', 'platform_type': 'PROVOR'}
`

**Comment by katieannemills** [comment]
Thanks very much for this report. A couple of things:
 - unfortunately, `platform_type` doesn't support the same comma separation and negation as `data`; that more sophisticated behavior is for `data` only, though I can see where you would have guessed it was more general. For everything else, you'll have to loop through requests, one for each platform type.
 - even so, this exposed a bug in the API where metadata filtering was just getting ignored if no matches were found, which is why you were getting back hits with other platform types (or any hits at all); this is now fixed in production, so the above request as written will return no matches, as it should.
